ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.plural(/$/, 's')
  inflect.plural(/([^aeéiou])$/i, '\1es')
  inflect.plural(/([aeiou]s)$/i, '\1')
  inflect.plural(/z$/i, 'ces')
  inflect.plural(/á([sn])$/i, 'a\1es')
  inflect.plural(/é([sn])$/i, 'e\1es')
  inflect.plural(/í([sn])$/i, 'i\1es')
  inflect.plural(/ó([sn])$/i, 'o\1es')
  inflect.plural(/ú([sn])$/i, 'u\1es')

  inflect.singular(/s$/, '')
  inflect.singular(/es$/, '')

  inflect.irregular('el', 'los')
  inflect.irregular('user', 'users')
  inflect.irregular('usersmodulo', 'usersmodulos')
  inflect.irregular('modulo', 'modulos')
  inflect.irregular('portafolio', 'portafolios')
  inflect.irregular('usersportafolio', 'usersportafolios')
  inflect.irregular('usersmodulo', 'usersmodulos')
  inflect.irregular('sede', 'sedes')
  inflect.irregular('tiposservicio', 'tiposservicios')
  inflect.irregular('cliente', 'clientes')
  inflect.irregular('intervalo', 'intervalos')
  inflect.irregular('intervaloshora', 'intervaloshoras')
  inflect.irregular('tiposagenda', 'tiposagendas')
  inflect.irregular('agenda', 'agendas')
  inflect.irregular('usersregistrado', 'usersregistrados')
  inflect.irregular('portafoliospersona', 'portafoliospersonas')
  inflect.irregular('fecha', 'fechas')
  inflect.irregular('migracion', 'migraciones')
  inflect.irregular('migracionescampo', 'migracionescampos')
  inflect.irregular('migracionesuser', 'migracionesusers')
  inflect.irregular('archivo', 'archivos')
  inflect.irregular('antecedente', 'antecedentes')
  inflect.irregular('persona', 'personas')
  inflect.irregular('centro', 'centros')
  inflect.irregular('personasevaluacion', 'personasevaluaciones')
  inflect.irregular('reporte', 'reportes')
  inflect.irregular('infgrupo', 'Infgrupos')
  inflect.irregular('infgrupostabla', 'infgrupostablas')
  inflect.irregular('infgrupostablascampo', 'infgrupostablascampos')
  inflect.irregular('personasobservacion', 'personasobservaciones')
  inflect.irregular('personasimagen', 'personasimagenes')
  inflect.irregular('fecha', 'fechas')

  inflect.irregular('tiposdocumento', 'tiposdocumentos')
  inflect.irregular('tiposimagen', 'tiposimagenes')
  inflect.irregular('tiposcuenta', 'tiposcuentas')
  inflect.irregular('tiposcontrato', 'tiposcontratos')
  inflect.irregular('municipio', 'municipios')
  inflect.irregular('empresa', 'empresas')
  inflect.irregular('contrato', 'contratos')
  inflect.irregular('contratosimagen', 'contratosimagenes')
  inflect.irregular('contratosuser', 'contratosusers')
  inflect.irregular('contratosmodificacion', 'contratosmodificaciones')
  inflect.irregular('contratosobservacion', 'contratosobservaciones')
  inflect.irregular('contratospago', 'contratospagos')
  inflect.irregular('empresassede', 'empresassedes')
  inflect.irregular('insumo', 'insumos')
  inflect.irregular('contratosinsumo', 'contratosinsumos')
  inflect.irregular('tiposarea', 'tiposareas')
  inflect.irregular('migracionesinsumo', 'migracionesinsumos')
  inflect.irregular('contratossede', 'contratossedes')
  inflect.irregular('tiposcargo', 'tiposcargos')
  inflect.irregular('contratoscargo', 'contratoscargos')
  inflect.irregular('contratosmaquinaria', 'contratosmaquinarias')
  inflect.irregular('contratosotro', 'contratosotros')

  inflect.irregular('contratossolicitud', 'contratossolicitudes')
  inflect.irregular('contratossolbitacora', 'contratossolbitacoras')
  inflect.irregular('contratossoldetalle', 'contratossoldetalles')

  inflect.irregular('userstemporal', 'userstemporales')
  inflect.irregular('proveedor', 'proveedores')
  inflect.irregular('proveedorescontacto', 'proveedorescontactos')
  inflect.irregular('proveedoresimagen', 'proveedoresimagenes')

  inflect.irregular('entrada', 'entradas')
  inflect.irregular('barrio', 'barrios')
  inflect.irregular('contratospersona', 'contratospersonas')

  inflect.irregular('contratosperexamen', 'contratosperexamenes')
  inflect.irregular('contratosperestado', 'contratosperestados')
  inflect.irregular('contratospergrupo', 'contratospergrupos')
  inflect.irregular('contratosperbitacora', 'contratosperbitacoras')
  inflect.irregular('iparametro', 'iparametros')
  inflect.irregular('contratosperagenda', 'contratosperagendas')
  inflect.irregular('personastemporal', 'personastemporales')
  inflect.irregular('contratossolotro', 'contratossolotros')

  inflect.irregular('contratossolimagen', 'contratossolimagenes')
  inflect.irregular('contratossolnota', 'contratossolnotas')


  inflect.irregular('contratosactividad', 'contratosactividades')
  inflect.irregular('contratosactejecucion', 'contratosactejecuciones')
  inflect.irregular('contratosactnota', 'contratosactnotas')

  inflect.irregular('contratosprefactura', 'contratosprefacturas')
  inflect.irregular('contratosprefdetalle', 'contratosprefdetalles')

  inflect.irregular('tiposnovedad', 'tiposnovedades')
  inflect.irregular('contratospernovedad', 'contratospernovedades')

  inflect.irregular('periodosliquidacion', 'periodosliquidaciones')
  inflect.irregular('contratospernomina', 'contratospernominas')
  inflect.irregular('contratostiposnovedad', 'contratostiposnovedades')
  inflect.irregular('contratosperfecha', 'contratosperfechas')

  inflect.irregular('contratosretencion', 'contratosretenciones')
  inflect.irregular('contratosprefretencion', 'contratosprefretenciones')

  inflect.irregular('tiposevaluacion', 'tiposevaluaciones')
  inflect.irregular('contratosgrupo', 'contratosgrupos')
  inflect.irregular('contratosactcodigosinfo', 'contratosactcodigosinfos')
  inflect.irregular('contratosactmcodigosinfo', 'contratosactmcodigosinfos')
  inflect.irregular('contratosautoinsumo', 'contratosautoinsumos')
  inflect.irregular('contratosprefimagen', 'contratosprefimagenes')
  inflect.irregular('contratosnodo', 'contratosnodos')
  inflect.irregular('contratosperuser', 'contratosperusers')
  inflect.irregular('tiposentidad', 'tiposentidades')
  inflect.irregular('contratosperembargo', 'contratosperembargos')
  inflect.irregular('contratosperprestamo', 'contratosperprestamos')
  inflect.irregular('contratosperrodamiento', 'contratosperrodamientos')
  inflect.irregular('contratosperdescuento', 'contratosperdescuentos')
  inflect.irregular('contratosprenimagen', 'contratosprenimagenes')
  inflect.irregular('solicitudesretiro', 'solicitudesretiros')
  inflect.irregular('contratosperliquidacion', 'contratosperliquidaciones')
  inflect.irregular('contratoscaractividad', 'contratoscaractividades')
  inflect.irregular('contratosperimagen', 'contratosperimagenes')
  inflect.irregular('contratosperliqnovedad', 'contratosperliqnovedades')
  inflect.irregular('contratosperlimagen', 'contratosperlimagenes')
  inflect.irregular('contratospermasiva', 'contratospermasivas')
  inflect.irregular('contratospermasdetalle', 'contratospermasdetalles')
  inflect.irregular('contratosprefcredito', 'contratosprefcreditos')
  inflect.irregular('contratosprefdebito', 'contratosprefdebitos')

  inflect.irregular('contratosperqueja', 'contratosperquejas')
  inflect.irregular('contratospersugerencia', 'contratospersugerencias')
  inflect.irregular('contratosperchequeo', 'contratosperchequeos')
  inflect.irregular('contratospernota', 'contratospernotas')
  inflect.irregular('usersreporte', 'usersreportes')

  inflect.irregular('eproveedorescompra', 'eproveedorescompras')
  inflect.irregular('eproveedorestempcompra', 'eproveedorestempcompras')
  inflect.irregular('eproveedorestemegreso', 'eproveedorestemegresos')
  inflect.irregular('egreso', 'egresos')
  inflect.irregular('egresosdetalle', 'egresosdetalles')
  inflect.irregular('eproveedoresrecibo', 'eproveedoresrecibos')
  inflect.irregular('eproveedorescredito', 'eproveedorescreditos')
  inflect.irregular('eproveedoresimagen', 'eproveedoresimagenes')

  inflect.irregular('concepto', 'conceptos')
  inflect.irregular('conceptosretencion', 'conceptosretenciones')
  inflect.irregular('eproveedorescompretencion', 'eproveedorescompretenciones')
  inflect.irregular('eproveedorescimagen', 'eproveedorescimagenes')
  inflect.irregular('egresosimagen', 'egresosimagenes')
  inflect.irregular('contratoscargosnota', 'contratoscargosnotas')
  inflect.irregular('contratoscargospersona', 'contratoscargospersonas')
  inflect.irregular('migracionesrodamiento', 'migracionesrodamientos')
  inflect.irregular('migracionesnovedad', 'migracionesnovedades')
  inflect.irregular('migracionessupervisor', 'migracionessupervisores')
  inflect.irregular('migracionescontrato', 'migracionescontratos')
  inflect.irregular('migracionesprorroga', 'migracionesprorrogas')
  inflect.irregular('contratosperfcontrol', 'contratosperfcontroles')
  inflect.irregular('portafoliosconfiguracion', 'portafoliosconfiguraciones')
  inflect.irregular('ejecucion', 'ejecuciones')
  inflect.irregular('contratosactnovedad', 'contratosactnovedades')
  inflect.irregular('contratosactnovuser', 'contratosactnovusers')
  inflect.irregular('contratosactnovnota', 'contratosactnovnotas')
  inflect.irregular('contratosactnovdoc', 'contratosactnovdocs')
  inflect.irregular('segumientoconsolidado', 'segumientoconsolidados')
  inflect.irregular('contratosproyecto', 'contratosproyectos')
  inflect.irregular('contratosprosede', 'contratosprosedes')
  #inflect.irregular('contratosproyecto', 'contratosproyectos')
  inflect.irregular('seguimientonodo', 'seguimientonodos')
  inflect.irregular('documentosfirma', 'documentosfirmas')
  inflect.irregular('contratosinsimagen', 'contratosinsimagenes')
  inflect.irregular('tiposnaporte', 'tiposnaportes')
  inflect.irregular('contratosperfact', 'contratosperfacts')
  inflect.irregular('contratosseccion', 'contratossecciones')
  inflect.irregular('parcargo', 'parcargos')
  inflect.irregular('parcargosdoc', 'parcargosdocs')
  inflect.irregular('migracionespersona', 'migracionespersonas')
  inflect.irregular('personasformulario', 'personasformularios')
  inflect.irregular('personasformulariosdoc', 'personasformulariosdocs')
  inflect.irregular('personasformulariosmensaje', 'personasformulariosmensajes')
  inflect.irregular('personasformulariosexamen', 'personasformulariosexamenes')
  inflect.irregular('migracionesexamen', 'migracionesexamenes')
  inflect.irregular('personasfordocsoporte', 'personasfordocsoportes')
  inflect.irregular('migracionesestado', 'migracionesestados')
  inflect.irregular('personasforexadoc', 'personasforexadocs')
  inflect.irregular('encuesta', 'encuestas')
  inflect.irregular('encuestapregunta', 'encuestapreguntas')
  inflect.irregular('encuestapreopcion', 'encuestapreopciones')
  inflect.irregular('personasforencuesta', 'personasforencuestas')
  inflect.irregular('erroresaporte', 'erroresaportes')
  inflect.irregular('contratosperfechasdoc', 'contratosperfechasdocs')
  inflect.irregular('contratosseguimiento', 'contratosseguimientos')
  inflect.irregular('contratoscargosact', 'contratoscargosacts')
  inflect.irregular('contratosperalerta', 'contratosperalertas')
  inflect.irregular('contratosperactob', 'contratosperactobs')
  inflect.irregular('contratosperlabora', 'contratosperlaboras')
  inflect.irregular('contratossecuser', 'contratossecusers')
  inflect.irregular('iparametrosuser', 'iparametrosusers')
  inflect.irregular('controlfirma', 'controlfirmas')

  inflect.irregular('migracionescuenta', 'migracionescuentas')
  inflect.irregular('controlformato', 'controlformatos')
  inflect.irregular('migracionesterminacion', 'migracionesterminaciones')
  inflect.irregular('migracionestelefono', 'migracionestelefonos')
  inflect.irregular('capacitacion', 'capacitaciones')
  inflect.irregular('capacitacionevaluacion', 'capacitacionevaluaciones')
  inflect.irregular('capacitacionevaopcion', 'capacitacionevaopciones')
  inflect.irregular('capacitaciondoc', 'capacitaciondocs')
  inflect.irregular('contratoscapacitacion', 'contratoscapacitaciones')
  inflect.irregular('contratoscapapersona', 'contratoscapapersonas')
  inflect.irregular('contratoscapapersona', 'contratoscapapersonas')
  inflect.irregular('contratoscaparesultado', 'contratoscaparesultados')
  inflect.irregular('tarea', 'tareas')
  inflect.irregular('tareasactividad', 'tareasactividades')
  inflect.irregular('tareasactdoc', 'tareasactdocs')
  inflect.irregular('tareasdoc', 'tareasdocs')
  inflect.irregular('audit', 'audits')
  inflect.irregular('migracionesactividad', 'migracionesactividades')
  inflect.irregular('contratosperproceso', 'contratosperprocesos')
  inflect.irregular('contratosperprodoc', 'contratosperprodocs')
  inflect.irregular('contratosperprocitacion', 'contratosperprocitaciones')
  inflect.irregular('contratosperprodescargo', 'contratosperprodescargos')
  inflect.irregular('contratosperprosancion', 'contratosperprosanciones')
  inflect.irregular('contratosperpronota', 'contratosperpronotas')
  inflect.irregular('bitacoraproceso', 'bitacoraprocesos')

  inflect.irregular('contratoscargosdetalle', 'contratoscargosdetalles')

  inflect.irregular('soporte', 'soportes')
  inflect.irregular('soportesnota', 'soportesnotas')
  inflect.irregular('soportesnotasimagen', 'soportesnotasimagenes')
  inflect.irregular('visitasdoc', 'visitasdocs')
  inflect.irregular('visitassede', 'visitassedes')
  inflect.irregular('evaluacion', 'evaluaciones')
  inflect.irregular('evaluacionesdetalle', 'evaluacionesdetalles')
  inflect.irregular('evaluacionescontrato', 'evaluacionescontratos')
  inflect.irregular('evaluacionesejecucion', 'evaluacionesejecuciones')
  inflect.irregular('evaluacionesejecucionesdoc', 'evaluacionesejecucionesdocs')
  inflect.irregular('visitasatencion', 'visitasatenciones')
  inflect.irregular('contratosservicio', 'contratosservicios')
  inflect.irregular('usersvisita', 'usersvisitas')

  inflect.irregular('contratossolepp', 'contratossolepps')
  inflect.irregular('contratossoleppsdetalle', 'contratossoleppsdetalles')
  inflect.irregular('contratossoleppsbitacora', 'contratossoleppsbitacoras')
  inflect.irregular('contratosentepp', 'contratosentepps')
  inflect.irregular('contratosenteppsdetalle', 'contratosenteppsdetalles')

  inflect.irregular('contratosperdotacion', 'contratosperdotaciones')
  inflect.irregular('variable', 'variables')
  inflect.irregular('formato', 'formatos')
  inflect.irregular('formatosvariable', 'formatosvariables')
  inflect.irregular('contratosperinventario', 'contratosperinventarios')
  inflect.irregular('contratosperinvdetalle', 'contratosperinvdetalles')
  inflect.irregular('contratosperinvatencion', 'contratosperinvatenciones')
  inflect.irregular('contratosperinvnota', 'contratosperinvnotas')
  inflect.irregular('contratosperdetallesdoc', 'contratosperdetallesdocs')
  inflect.irregular('insumosficha', 'insumosfichas')
  inflect.irregular('contratossoleppsdoc', 'contratossoleppsdocs')
  inflect.irregular('contratossoleppsatencion', 'contratossoleppsatenciones')
  inflect.irregular('contratosentepp', 'contratosentepps')
  inflect.irregular('graph', 'graph')
  inflect.irregular('contratosenteppsfirma', 'contratosenteppsfirmas')
  inflect.irregular('usersparametro', 'usersparametros')
  inflect.irregular('contratosperinvacta', 'contratosperinvactas')
  inflect.irregular('contratosperdotacion', 'contratosperdotaciones')
  inflect.irregular('contratosperdotadicional', 'contratosperdotadicionales')
  inflect.irregular('dashepp', 'dashepps')
  inflect.irregular('compromiso', 'compromisos')
  inflect.irregular('visitashallazgo', 'visitashallazgos')
  inflect.irregular('visitasasistente', 'visitasasistentes')
  inflect.irregular('analisisepp', 'analisisepps')
  inflect.irregular('contratossoleppscontrol', 'contratossoleppscontroles')
  inflect.irregular('migracionestalla', 'migracionestallas')
  inflect.irregular('veriservicio','veriservicios')
  inflect.irregular('veriserviciosuser','veriserviciosusers')
  inflect.irregular('veriserviciosagenda','veriserviciosagendas')
  inflect.irregular('veriserviciositem','veriserviciositems')
  inflect.irregular('veriserviciosinota','veriserviciosinotas')
  inflect.irregular('veriserviciosiimagen','veriserviciosiimagenes')
  inflect.irregular('veriserviciosicompromiso','veriserviciosicompromisos')
  inflect.irregular('veriserviciosicimagen','veriserviciosicimagenes')
  inflect.irregular('veriserviciosasoporte','veriserviciosasoportes')
  inflect.irregular('veriserviciosagendasdato','veriserviciosagendasdatos')
  inflect.irregular('migracionessede', 'migracionessedes')

  inflect.irregular('formato', 'formatos')
  inflect.irregular('variable', 'variables')
  inflect.irregular('formatosvariable', 'formatosvariables')
  inflect.irregular('iparametrosformato', 'iparametrosformatos')
  inflect.irregular('notificacionesplataforma','notificacionesplataformas')
  inflect.irregular('eventosuser', 'eventosusers')
  inflect.irregular('eventoseliminado', 'eventoseliminados')

  # FIX Rails 7: login_activity → login_activities (evita login_activityes)
  inflect.irregular 'login_activity', 'login_activities'
end




